import { useState, useEffect, useCallback } from 'react';
import {
  getAIRiskAssessment,
  getAIConsolidation,
  getAIComplianceReport,
  type DetectedApp,
  type RiskAssessmentEntry,
  type ConsolidationEntry,
  type ComplianceReport,
} from '../services/api';

interface AIInsightsProps {
  detectedApps: DetectedApp[];
}

const RISK_COLORS: Record<string, string> = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#22c55e',
};

const SCORE_LABEL = (score: number) =>
  score >= 80 ? 'CRITICAL' : score >= 60 ? 'HIGH' : score >= 40 ? 'MEDIUM' : 'LOW';

function generateMarkdownReport(report: ComplianceReport, apps: DetectedApp[]): string {
  const totalSpend = apps.reduce((s, a) => s + a.typical_price, 0);
  const highRisk = apps.filter(a => a.risk_level === 'high' || a.risk_level === 'critical').length;
  return `# Shadow SaaS Compliance Report
**Organization:** GrowthLabs Inc.
**Generated:** ${new Date(report.generatedAt).toLocaleString()}
**Prepared by:** Shadow SaaS Detector (Automated)

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Shadow Apps | ${report.totalApps} |
| Monthly Shadow Spend | $${totalSpend} |
| Annual Projected Cost | $${totalSpend * 12} |
| Compliance Score | ${report.complianceScore}/100 |
| Critical Issues | ${report.criticalIssues} |
| High-Risk Applications | ${highRisk} |

${report.summary}

## Risk Breakdown

${report.issues.map(i => `### ${i.app} — ${i.severity.toUpperCase()}
- **Policy:** ${i.policy}
- **Issue:** ${i.description}
- **Recommendation:** ${i.recommendation}
`).join('\n')}

## Action Plan
${report.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n')}

## 12-Month Forecast
${report.forecast12Months}

---
*This report was auto-generated by Shadow SaaS Detector. For questions, contact your IT administrator.*
`;
}

function exportComplianceReport(report: ComplianceReport) {
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Shadow SaaS Compliance Report</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:800px;margin:0 auto;padding:2rem;color:#1e293b;font-size:14px;line-height:1.6}
  h1{color:#1e40af;border-bottom:3px solid #3b82f6;padding-bottom:0.5rem}
  h2{color:#1e40af;margin-top:2rem;border-bottom:1px solid #e2e8f0;padding-bottom:0.25rem}
  .score-box{display:inline-block;background:${report.complianceScore >= 80 ? '#dcfce7' : report.complianceScore >= 60 ? '#fef9c3' : '#fee2e2'};color:${report.complianceScore >= 80 ? '#166534' : report.complianceScore >= 60 ? '#854d0e' : '#991b1b'};font-size:2rem;font-weight:800;padding:0.5rem 1.5rem;border-radius:12px;margin:0.5rem 0}
  table{width:100%;border-collapse:collapse;margin:1rem 0}
  th,td{padding:8px 12px;border:1px solid #e2e8f0;text-align:left}
  th{background:#f1f5f9;font-weight:600}
  .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700;text-transform:uppercase}
  .badge-critical{background:#fee2e2;color:#991b1b}
  .badge-high{background:#ffedd5;color:#9a3412}
  .badge-medium{background:#fef9c3;color:#854d0e}
  .badge-low{background:#dcfce7;color:#166534}
  .action-item{padding:8px 0;border-bottom:1px solid #f1f5f9}
  .forecast{background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:1rem;margin-top:1rem}
  .footer{margin-top:3rem;padding-top:1rem;border-top:2px solid #e2e8f0;color:#94a3b8;font-size:12px}
  @media print{body{padding:0}}
</style></head><body>
<h1>🔍 Shadow SaaS Compliance Report</h1>
<p><strong>Organization:</strong> GrowthLabs Inc. &nbsp;|&nbsp; <strong>Date:</strong> ${new Date(report.generatedAt).toLocaleDateString()}</p>

<h2>Compliance Score</h2>
<div class="score-box">${report.complianceScore}/100</div>
<p>${report.summary}</p>

<h2>Summary Metrics</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total Apps Reviewed</td><td>${report.totalApps}</td></tr>
<tr><td>Critical Issues</td><td style="color:#dc2626;font-weight:700">${report.criticalIssues}</td></tr>
<tr><td>Total Issues Found</td><td>${report.issues.length}</td></tr>
<tr><td>Action Items</td><td>${report.actionItems.length}</td></tr>
</table>

<h2>Identified Issues</h2>
<table>
<tr><th>Application</th><th>Policy</th><th>Severity</th><th>Description</th><th>Recommendation</th></tr>
${report.issues.map(i => `<tr>
<td><strong>${i.app}</strong></td>
<td>${i.policy}</td>
<td><span class="badge badge-${i.severity}">${i.severity}</span></td>
<td>${i.description}</td>
<td>${i.recommendation}</td>
</tr>`).join('')}
</table>

<h2>Action Plan</h2>
${report.actionItems.map((item, i) => `<div class="action-item"><strong>${i + 1}.</strong> ${item}</div>`).join('')}

<div class="forecast">
<h3>📅 12-Month Forecast</h3>
<p>${report.forecast12Months}</p>
</div>

<div class="footer">
<p>This report was auto-generated by <strong>Shadow SaaS Detector</strong> on ${new Date().toLocaleString()}.</p>
<p>Classification: CONFIDENTIAL — For internal use only.</p>
</div>
</body></html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

export default function AIInsights({ detectedApps }: AIInsightsProps) {
  const [activePanel, setActivePanel] = useState<'risk' | 'consolidation' | 'compliance'>('risk');

  // Risk Assessment state
  const [riskData, setRiskData] = useState<Record<string, RiskAssessmentEntry> | null>(null);
  const [riskLoading, setRiskLoading] = useState(false);
  const [riskError, setRiskError] = useState<string | null>(null);

  // Consolidation state
  const [consolidationData, setConsolidationData] = useState<ConsolidationEntry[] | null>(null);
  const [consolidationLoading, setConsolidationLoading] = useState(false);
  const [consolidationError, setConsolidationError] = useState<string | null>(null);

  // Compliance state
  const [complianceData, setComplianceData] = useState<ComplianceReport | null>(null);
  const [complianceLoading, setComplianceLoading] = useState(false);
  const [complianceError, setComplianceError] = useState<string | null>(null);

  // Auto-load risk assessment when apps are available
  const loadRisk = useCallback(async () => {
    setRiskLoading(true);
    setRiskError(null);
    try {
      const data = await getAIRiskAssessment(detectedApps);
      setRiskData(data);
    } catch {
      setRiskError('Risk assessment failed — check backend connection.');
    } finally {
      setRiskLoading(false);
    }
  }, [detectedApps]);

  const loadConsolidation = useCallback(async () => {
    setConsolidationLoading(true);
    setConsolidationError(null);
    try {
      const data = await getAIConsolidation(detectedApps);
      setConsolidationData(data);
    } catch {
      setConsolidationError('Consolidation analysis failed.');
    } finally {
      setConsolidationLoading(false);
    }
  }, [detectedApps]);

  const loadCompliance = useCallback(async () => {
    setComplianceLoading(true);
    setComplianceError(null);
    try {
      const data = await getAIComplianceReport(detectedApps);
      setComplianceData(data);
    } catch {
      setComplianceError('Compliance report generation failed.');
    } finally {
      setComplianceLoading(false);
    }
  }, [detectedApps]);

  useEffect(() => {
    if (detectedApps.length > 0 && !riskData && !riskLoading) {
      loadRisk();
    }
  }, [detectedApps.length, riskData, riskLoading, loadRisk]);

  const handleTabChange = (panel: typeof activePanel) => {
    setActivePanel(panel);
    if (panel === 'consolidation' && !consolidationData && !consolidationLoading) loadConsolidation();
    if (panel === 'compliance' && !complianceData && !complianceLoading) loadCompliance();
  };

  if (detectedApps.length === 0) {
    return (
      <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-secondary)' }}>
        <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🤖</div>
        <p>Upload company data first to run AI analysis.</p>
      </div>
    );
  }

  return (
    <div data-testid="ai-insights">
      <style>{`
        @keyframes aiInsightsPulseDot {
          0%, 100% { opacity: 1; box-shadow: 0 0 0 0 rgba(34,197,94,0.5); }
          50% { opacity: 0.75; box-shadow: 0 0 0 6px rgba(34,197,94,0); }
        }
      `}</style>
      <div style={{ marginBottom: '1rem' }}>
        <h2 style={{ marginBottom: '0.6rem' }}>🤖 AI Insights</h2>
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.5rem',
            padding: '0.4rem 0.75rem',
            borderRadius: '9999px',
            background: 'rgba(59,130,246,0.12)',
            border: '1px solid rgba(59,130,246,0.3)',
            fontSize: '0.78rem',
            color: 'var(--text-primary)',
            fontWeight: 600,
          }}
          data-testid="LiveAI"
        >
          <span
            style={{
              width: '8px',
              height: '8px',
              borderRadius: '50%',
              background: '#22c55e',
              animation: 'aiInsightsPulseDot 1.4s ease-in-out infinite',
            }}
            className="pulse-dot"
          />
          Powered by Gemini 1.5 Flash · Live AI Analysis
        </div>
      </div>
      {/* Sub-tabs */}
      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
        {(
          [
            { id: 'risk', label: '🔴 Risk Assessment', desc: 'Per-app threat scoring' },
            { id: 'consolidation', label: '🎯 Smart Consolidation', desc: 'Remove duplicates' },
            { id: 'compliance', label: '📋 Compliance Audit', desc: 'GDPR / CCPA' },
          ] as const
        ).map((t) => (
          <button
            key={t.id}
            onClick={() => handleTabChange(t.id)}
            style={{
              padding: '0.6rem 1.2rem',
              borderRadius: '8px',
              border: '1.5px solid',
              borderColor: activePanel === t.id ? 'var(--accent)' : 'var(--border)',
              background: activePanel === t.id ? 'var(--accent)' : 'var(--card-bg)',
              color: 'var(--text-primary)',
              cursor: 'pointer',
              fontWeight: activePanel === t.id ? 700 : 400,
              fontSize: '0.85rem',
              transition: 'all 0.2s',
            }}
            data-testid={`ai-tab-${t.id}`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Risk Assessment Panel ── */}
      {activePanel === 'risk' && (
        <div data-testid="risk-panel">
          <div className="section-header" style={{ marginBottom: '1rem' }}>
            <h2>🔴 AI Risk Assessment</h2>
            <button className="btn btn-secondary btn-sm" onClick={loadRisk} disabled={riskLoading}>
              {riskLoading ? '⏳ Analyzing…' : '↻ Re-run'}
            </button>
          </div>

          {riskLoading && (
            <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
              <div className="spinner" style={{ margin: '0 auto 1rem' }} />
              <p>AI is analyzing {detectedApps.length} apps for security risks…</p>
            </div>
          )}

          {riskError && <div className="error-banner">{riskError}</div>}

          {riskData && !riskLoading && (
            <>
              {/* Summary bar */}
              <div className="stats-grid" style={{ marginBottom: '1.5rem' }}>
                {(['critical', 'high', 'medium', 'low'] as const).map((lvl) => {
                  const count = Object.values(riskData).filter((a) => a.level === lvl).length;
                  return (
                    <div key={lvl} className="stat-card">
                      <div className="stat-label">{lvl.toUpperCase()}</div>
                      <div
                        className="stat-value"
                        style={{ color: RISK_COLORS[lvl] }}
                      >
                        {count}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* App risk cards */}
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
                  gap: '1rem',
                }}
              >
                {Object.entries(riskData)
                  .sort(([, a], [, b]) => b.score - a.score)
                  .map(([appName, entry]) => (
                    <div
                      key={appName}
                      className="app-card"
                      style={{ borderLeft: `3px solid ${RISK_COLORS[entry.level]}` }}
                      data-testid={`risk-card-${appName.replace(/\s+/g, '-')}`}
                    >
                      <div className="app-card-header">
                        <h3>{appName}</h3>
                        <span
                          className={`risk-badge ${entry.level}`}
                          style={{ fontWeight: 700 }}
                        >
                          {entry.score}/100
                        </span>
                      </div>
                      <div
                        style={{
                          fontSize: '0.8rem',
                          color: RISK_COLORS[entry.level],
                          fontWeight: 600,
                          marginBottom: '0.5rem',
                        }}
                      >
                        {SCORE_LABEL(entry.score)} RISK · {entry.category}
                      </div>
                      <p
                        style={{
                          fontSize: '0.82rem',
                          color: 'var(--text-secondary)',
                          marginBottom: '0.5rem',
                          lineHeight: 1.5,
                        }}
                      >
                        {entry.reasoning}
                      </p>
                      {entry.mainRisks.length > 0 && (
                        <ul
                          style={{
                            margin: '0 0 0.5rem',
                            paddingLeft: '1.1rem',
                            fontSize: '0.8rem',
                            color: 'var(--text-secondary)',
                          }}
                        >
                          {entry.mainRisks.map((r, i) => (
                            <li key={i}>{r}</li>
                          ))}
                        </ul>
                      )}
                      {entry.recommendations.length > 0 && (
                        <div
                          style={{
                            background: 'var(--success-bg, rgba(34,197,94,0.08))',
                            borderRadius: '6px',
                            padding: '0.4rem 0.6rem',
                            fontSize: '0.78rem',
                            color: 'var(--success)',
                          }}
                        >
                          💡 {entry.recommendations[0]}
                        </div>
                      )}
                    </div>
                  ))}
              </div>
            </>
          )}
        </div>
      )}

      {/* ── Consolidation Panel ── */}
      {activePanel === 'consolidation' && (
        <div data-testid="consolidation-panel">
          <div className="section-header" style={{ marginBottom: '1rem' }}>
            <h2>🎯 Smart Consolidation</h2>
            <button
              className="btn btn-secondary btn-sm"
              onClick={loadConsolidation}
              disabled={consolidationLoading}
            >
              {consolidationLoading ? '⏳ Analyzing…' : '↻ Re-run'}
            </button>
          </div>

          {consolidationLoading && (
            <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
              <div className="spinner" style={{ margin: '0 auto 1rem' }} />
              <p>AI is finding consolidation opportunities…</p>
            </div>
          )}

          {consolidationError && <div className="error-banner">{consolidationError}</div>}

          {consolidationData && !consolidationLoading && (
            <>
              {/* Total savings banner */}
              {(() => {
                const totalAnnual = consolidationData.reduce(
                  (s, r) => s + r.estimatedSavings,
                  0
                );
                return (
                  totalAnnual > 0 && (
                    <div
                      style={{
                        background: 'rgba(34,197,94,0.1)',
                        border: '1.5px solid var(--success)',
                        borderRadius: '10px',
                        padding: '1rem 1.5rem',
                        marginBottom: '1.5rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '1rem',
                      }}
                    >
                      <span style={{ fontSize: '2rem' }}>💰</span>
                      <div>
                        <div
                          style={{
                            fontSize: '1.5rem',
                            fontWeight: 700,
                            color: 'var(--success)',
                          }}
                        >
                          ${totalAnnual.toLocaleString()} / year
                        </div>
                        <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                          estimated annual savings from AI-recommended consolidation
                        </div>
                      </div>
                    </div>
                  )
                );
              })()}

              {consolidationData.map((rec) => (
                <div
                  key={rec.category}
                  className="app-card"
                  style={{ marginBottom: '1rem' }}
                  data-testid={`consolidation-card-${rec.category}`}
                >
                  <div className="app-card-header">
                    <h3>📁 {rec.category}</h3>
                    {rec.estimatedSavings > 0 && (
                      <span
                        style={{
                          background: 'rgba(34,197,94,0.15)',
                          color: 'var(--success)',
                          borderRadius: '6px',
                          padding: '0.25rem 0.75rem',
                          fontWeight: 700,
                          fontSize: '0.85rem',
                        }}
                      >
                        Save ${rec.estimatedSavings.toLocaleString()}/yr
                      </span>
                    )}
                  </div>
                  <p
                    style={{
                      fontSize: '0.83rem',
                      color: 'var(--text-secondary)',
                      margin: '0.5rem 0 0.75rem',
                      lineHeight: 1.5,
                    }}
                  >
                    {rec.reasoning}
                  </p>
                  {rec.keep.length > 0 && (
                    <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '0.5rem' }}>
                      {rec.keep.map((k) => (
                        <span
                          key={k}
                          style={{
                            background: 'rgba(34,197,94,0.15)',
                            color: 'var(--success)',
                            borderRadius: '6px',
                            padding: '0.2rem 0.6rem',
                            fontSize: '0.8rem',
                            fontWeight: 600,
                          }}
                        >
                          ✓ Keep: {k}
                        </span>
                      ))}
                      {rec.remove.map((r) => (
                        <span
                          key={r}
                          style={{
                            background: 'rgba(239,68,68,0.1)',
                            color: '#ef4444',
                            borderRadius: '6px',
                            padding: '0.2rem 0.6rem',
                            fontSize: '0.8rem',
                            fontWeight: 600,
                          }}
                        >
                          ✗ Remove: {r}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              ))}

              {consolidationData.every((r) => r.remove.length === 0) && (
                <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
                  ✅ No duplicate categories found — stack is already optimised.
                </div>
              )}
            </>
          )}
        </div>
      )}

      {/* ── Compliance Panel ── */}
      {activePanel === 'compliance' && (
        <div data-testid="compliance-panel">
          <div className="section-header" style={{ marginBottom: '1rem' }}>
            <h2>📋 Compliance Audit</h2>
            <button
              className="btn btn-secondary btn-sm"
              onClick={loadCompliance}
              disabled={complianceLoading}
            >
              {complianceLoading ? '⏳ Generating…' : '↻ Re-run'}
            </button>
          </div>

          {complianceLoading && (
            <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
              <div className="spinner" style={{ margin: '0 auto 1rem' }} />
              <p>AI is auditing your SaaS stack for GDPR / CCPA issues…</p>
            </div>
          )}

          {complianceError && <div className="error-banner">{complianceError}</div>}

          {complianceData && !complianceLoading && (
            <>
              {/* Score header */}
              <div className="stats-grid" style={{ marginBottom: '1.5rem' }}>
                <div className="stat-card">
                  <div className="stat-label">Compliance Score</div>
                  <div
                    className="stat-value"
                    style={{
                      color:
                        complianceData.complianceScore >= 80
                          ? 'var(--success)'
                          : complianceData.complianceScore >= 60
                          ? '#eab308'
                          : '#ef4444',
                    }}
                    data-testid="compliance-score"
                  >
                    {complianceData.complianceScore}
                    <span style={{ fontSize: '1rem', fontWeight: 400 }}>/100</span>
                  </div>
                </div>
                <div className="stat-card">
                  <div className="stat-label">Critical Issues</div>
                  <div className="stat-value text-danger">{complianceData.criticalIssues}</div>
                </div>
                <div className="stat-card">
                  <div className="stat-label">Apps Reviewed</div>
                  <div className="stat-value text-accent">{complianceData.totalApps}</div>
                </div>
                <div className="stat-card">
                  <div className="stat-label">Action Items</div>
                  <div className="stat-value text-warning">{complianceData.actionItems.length}</div>
                </div>
              </div>

              {/* Summary */}
              <div
                style={{
                  background: 'var(--card-bg)',
                  border: '1px solid var(--border)',
                  borderRadius: '10px',
                  padding: '1rem',
                  marginBottom: '1.5rem',
                  fontSize: '0.88rem',
                  lineHeight: 1.6,
                  color: 'var(--text-secondary)',
                }}
              >
                <strong style={{ color: 'var(--text-primary)' }}>Summary: </strong>
                {complianceData.summary}
              </div>

              {/* Issues */}
              {complianceData.issues.length > 0 && (
                <>
                  <h3 style={{ marginBottom: '0.75rem', fontSize: '1rem' }}>⚠️ Identified Issues</h3>
                  {complianceData.issues.map((issue, idx) => (
                    <div
                      key={idx}
                      className="app-card"
                      style={{
                        marginBottom: '0.75rem',
                        borderLeft: `3px solid ${RISK_COLORS[issue.severity]}`,
                      }}
                    >
                      <div className="app-card-header">
                        <h4 style={{ fontSize: '0.9rem' }}>{issue.app}</h4>
                        <span
                          className={`risk-badge ${issue.severity}`}
                        >
                          {issue.severity}
                        </span>
                      </div>
                      <div style={{ fontSize: '0.78rem', color: '#888', marginBottom: '0.25rem' }}>
                        Policy: {issue.policy}
                      </div>
                      <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '0.4rem' }}>
                        {issue.description}
                      </p>
                      <div
                        style={{
                          background: 'rgba(34,197,94,0.08)',
                          borderRadius: '6px',
                          padding: '0.4rem 0.6rem',
                          fontSize: '0.78rem',
                          color: 'var(--success)',
                        }}
                      >
                        💡 Fix: {issue.recommendation}
                      </div>
                    </div>
                  ))}
                </>
              )}

              {/* Action Items */}
              {complianceData.actionItems.length > 0 && (
                <>
                  <h3 style={{ margin: '1.5rem 0 0.75rem', fontSize: '1rem' }}>✅ Action Plan</h3>
                  <ol
                    style={{
                      margin: 0,
                      paddingLeft: '1.5rem',
                      fontSize: '0.88rem',
                      lineHeight: 1.9,
                      color: 'var(--text-secondary)',
                    }}
                  >
                    {complianceData.actionItems.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ol>
                </>
              )}

              {/* Forecast */}
              <div
                style={{
                  marginTop: '1.5rem',
                  background: 'rgba(139,92,246,0.08)',
                  border: '1px solid rgba(139,92,246,0.3)',
                  borderRadius: '10px',
                  padding: '1rem',
                  fontSize: '0.85rem',
                  color: 'var(--text-secondary)',
                }}
              >
                <strong style={{ color: 'var(--text-primary)' }}>📅 12-Month Forecast: </strong>
                {complianceData.forecast12Months}
              </div>

              {/* Export Report Button */}
              <div style={{ marginTop: '1.5rem', display: 'flex', gap: '0.75rem' }}>
                <button
                  className="btn btn-primary"
                  onClick={() => exportComplianceReport(complianceData)}
                >
                  📄 Export PDF Report
                </button>
                <button
                  className="btn btn-secondary"
                  onClick={() => {
                    const md = generateMarkdownReport(complianceData, detectedApps);
                    const blob = new Blob([md], { type: 'text/markdown' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `compliance-report-${new Date().toISOString().slice(0,10)}.md`;
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                >
                  📋 Export Markdown
                </button>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
